### ISSUE TITLE
Easy GitHub Actions integration

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixfmt#180]
There should be some way for people to easily start enforcing official `nixfmt` formatting on their GitHub repos. A GitHub Action workflow would be great for that.

See https://github.com/NixOS/nixpkgs/pull/299578#issuecomment-2027854127 for more context

**Comment by gabyx** [comment]
Although Github actions are a good first solution, it would be nice to just have a `nix run nixfmt#format <git-diff-args>` or something along these lines, so that other people no using Github Actions also can use it directly in a Nixfied container.
If I would do this, I would directly head for a `nix run ??? main...pr-branch` thing and then add the Github Action which could only be (not sure) wrapping this nix call. So everybody with a CI, or a local workflow can just do that and it works.

The `--check` option would just do the thing in a temp. folder and report if diffs happened or not.
