### ISSUE TITLE
Formatting unquotes interpolation

### ISSUE THREAD

**Issue by mmarx** [NixOS/nixfmt#197]
Consider `foo.nix`:
```nix
''
  O=''\'''${A}'
''
```

Formatting changes the semantics of this, turning it into an interpolation:
```nix
''
  O='''${A}'
''
```

```
foo.nix: Parses differently after formatting. This is a bug in nixfmt. Please report it at https://github.com/NixOS/nixfmt

Before formatting:
Term (IndentedString (Ann [] [[TextPart "O='''${A}'"],[]] Nothing))

After formatting:
Term (IndentedString (Ann [] [[TextPart "O='''",Interpolation Term (Token (Ann [] (Identifier "A") Nothing)),TextPart "'"],[]] Nothing))
```

**Comment by piegamesde** [comment]
This language is cursed beyond repair, and I see no hope in fixing this without a proper formal specification of its string syntax and semantics.

**Comment by infinisil** [comment]
Bumping this higher, since it's a correctness bug and is kind of blocking for https://github.com/NixOS/nixpkgs/pull/322537. @dasJ looked into it in todays meeting, I'll copy the notes here too:

- We discovered the relevant bits from the Nix lexer [here](https://github.com/NixOS/nix/blob/052f1320ddf72d617e337479ff1bf22cb4ee682a/src/libexpr/lexer.l#L182-L205)
- These should be relatively directly portable to Haskell (current code around [here](https://github.com/NixOS/nixfmt/blob/c67a7b65906bd2432730929bd0e4957659c95b8e/src/Nixfmt/Parser.hs#L192-L207))
- @Sereja313 recommended [this tutorial on Megaparsec](https://markkarpov.com/tutorial/megaparsec.html) by Mark Karpov

**Comment by dasJ** [comment]
More details from the debugging session: It's probably the parser. The example string can be minimized to `''\'''${A}`. Nixfmt parses this as:
```
Term
    ( IndentedString
        ( Ann []
            [
                [ TextPart "'''${A}" ]
            , []
            ] Nothing
        )
    )
```

while nix parses it as
```
"'\${A}\n"
```

It probably dies because the first 4 characters (`''\'`) get converted to `'` and the rest gets converted to `\${A}` (at least this is what nix does) while nixfmt converts the second part to `''${A}` which is incorrect. I have no idea why but this only happens when the two tokens are combined.
